deploy:
  machine_name: "minimoi.mynetgear.com"
  port: 8886
  target_directory: "/opt/character/"
  app_prefix: "/character"

models:
  - Qwen/Qwen2.5-72B-Instruct
  - meta-llama/Llama-3.2-3B-Instruct
  - google/gemma-3-27b-it:featherless-ai
  - openai/gpt-oss-120b:groq
